[tool.poetry]
name = "fit"
version = "1.4.0-beta"
description = "FIT is a Python3 application for forensic acquisition of contents like web pages, emails, social media, etc. directly from the internet."
authors = ["Fit Project <info@fit-project.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
ntplib = "^0.4.0"
numpy = "^1.24.1"
PyQt5 = "^5.15.8"
pywebcopy = "^7.0.2"
SQLAlchemy = "^2.0.0"
pyqtwebengine = "^5.15.6"
pyshark = "^0.4.3"
opencv-python = "^4.5.1.48"
pyautogui = "^0.9.52"
pillow = "^9.4.0"
python-whois = "^0.8.0"
xhtml2pdf = "^0.2.9"
PyPDF2 = "^3.0.1"
sslkeylog = "^0.4.0"
nslookup = "^1.7.0"
scapy = "^2.5.0"
instaloader = "^4.9.6"
pyzmail36 = "^1.0.5"
rfc3161ng = "^2.1.3"
mitmproxy = "^9.0.1"
warcio = "^1.7.4"
wacz = "^0.4.7"
brotlipy = "^0.7.0"
bs4 = "^0.0.1"
pytube = "^12.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
